/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { createStart } from '@tanstack/react-start'

import type { getRouter } from './router.tsx'
import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardSuggestionsIndexRouteImport } from './routes/_authed/dashboard/suggestions/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicCapabilitiesSlugSubslugRouteImport } from './routes/_public/capabilities/$slug/$subslug'
import { Route as PublicCapabilitiesSlugIndexRouteImport } from './routes/_public/capabilities/$slug/index'
import { Route as PublicCapabilitiesIndexRouteImport } from './routes/_public/capabilities/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicJobsSlugIndexRouteImport } from './routes/_public/jobs/$slug/index'
import { Route as PublicJobsIndexRouteImport } from './routes/_public/jobs/index'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicReportsIndexRouteImport } from './routes/_public/reports/index'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicTechnologiesIndexRouteImport } from './routes/_public/technologies/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as AdminCapabilitiesSlugSubslugEditRouteImport } from './routes/admin/capabilities/$slug/$subslug/edit'
import { Route as AdminCapabilitiesSlugAddRouteImport } from './routes/admin/capabilities/$slug/add'
import { Route as AdminCapabilitiesSlugEditRouteImport } from './routes/admin/capabilities/$slug/edit'
import { Route as AdminCapabilitiesSlugIndexRouteImport } from './routes/admin/capabilities/$slug/index'
import { Route as AdminCapabilitiesAddRouteImport } from './routes/admin/capabilities/add'
import { Route as AdminCapabilitiesIndexRouteImport } from './routes/admin/capabilities/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminJobsSlugEditRouteImport } from './routes/admin/jobs/$slug/edit'
import { Route as AdminJobsSlugIndexRouteImport } from './routes/admin/jobs/$slug/index'
import { Route as AdminJobsAddRouteImport } from './routes/admin/jobs/add'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCapabilitiesIndexRoute = AdminCapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicTechnologiesIndexRoute = PublicTechnologiesIndexRouteImport.update({
  id: '/technologies/',
  path: '/technologies/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicReportsIndexRoute = PublicReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicJobsIndexRoute = PublicJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCapabilitiesIndexRoute = PublicCapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsAddRoute = AdminJobsAddRouteImport.update({
  id: '/jobs/add',
  path: '/jobs/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCapabilitiesAddRoute = AdminCapabilitiesAddRouteImport.update({
  id: '/capabilities/add',
  path: '/capabilities/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsSlugIndexRoute = AdminJobsSlugIndexRouteImport.update({
  id: '/jobs/$slug/',
  path: '/jobs/$slug/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCapabilitiesSlugIndexRoute =
  AdminCapabilitiesSlugIndexRouteImport.update({
    id: '/capabilities/$slug/',
    path: '/capabilities/$slug/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const PublicJobsSlugIndexRoute = PublicJobsSlugIndexRouteImport.update({
  id: '/jobs/$slug/',
  path: '/jobs/$slug/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCapabilitiesSlugIndexRoute =
  PublicCapabilitiesSlugIndexRouteImport.update({
    id: '/capabilities/$slug/',
    path: '/capabilities/$slug/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AuthedDashboardSuggestionsIndexRoute =
  AuthedDashboardSuggestionsIndexRouteImport.update({
    id: '/dashboard/suggestions/',
    path: '/dashboard/suggestions/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AdminJobsSlugEditRoute = AdminJobsSlugEditRouteImport.update({
  id: '/jobs/$slug/edit',
  path: '/jobs/$slug/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCapabilitiesSlugEditRoute =
  AdminCapabilitiesSlugEditRouteImport.update({
    id: '/capabilities/$slug/edit',
    path: '/capabilities/$slug/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCapabilitiesSlugAddRoute =
  AdminCapabilitiesSlugAddRouteImport.update({
    id: '/capabilities/$slug/add',
    path: '/capabilities/$slug/add',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const PublicCapabilitiesSlugSubslugRoute =
  PublicCapabilitiesSlugSubslugRouteImport.update({
    id: '/capabilities/$slug/$subslug',
    path: '/capabilities/$slug/$subslug',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AdminCapabilitiesSlugSubslugEditRoute =
  AdminCapabilitiesSlugSubslugEditRouteImport.update({
    id: '/capabilities/$slug/$subslug/edit',
    path: '/capabilities/$slug/$subslug/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/capabilities/add': typeof AdminCapabilitiesAddRoute
  '/admin/jobs/add': typeof AdminJobsAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/capabilities/': typeof PublicCapabilitiesIndexRoute
  '/jobs/': typeof PublicJobsIndexRoute
  '/reports/': typeof PublicReportsIndexRoute
  '/technologies/': typeof PublicTechnologiesIndexRoute
  '/admin/capabilities/': typeof AdminCapabilitiesIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/capabilities/$slug/$subslug': typeof PublicCapabilitiesSlugSubslugRoute
  '/admin/capabilities/$slug/add': typeof AdminCapabilitiesSlugAddRoute
  '/admin/capabilities/$slug/edit': typeof AdminCapabilitiesSlugEditRoute
  '/admin/jobs/$slug/edit': typeof AdminJobsSlugEditRoute
  '/dashboard/suggestions/': typeof AuthedDashboardSuggestionsIndexRoute
  '/capabilities/$slug/': typeof PublicCapabilitiesSlugIndexRoute
  '/jobs/$slug/': typeof PublicJobsSlugIndexRoute
  '/admin/capabilities/$slug/': typeof AdminCapabilitiesSlugIndexRoute
  '/admin/jobs/$slug/': typeof AdminJobsSlugIndexRoute
  '/admin/capabilities/$slug/$subslug/edit': typeof AdminCapabilitiesSlugSubslugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/capabilities/add': typeof AdminCapabilitiesAddRoute
  '/admin/jobs/add': typeof AdminJobsAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/capabilities': typeof PublicCapabilitiesIndexRoute
  '/jobs': typeof PublicJobsIndexRoute
  '/reports': typeof PublicReportsIndexRoute
  '/technologies': typeof PublicTechnologiesIndexRoute
  '/admin/capabilities': typeof AdminCapabilitiesIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/capabilities/$slug/$subslug': typeof PublicCapabilitiesSlugSubslugRoute
  '/admin/capabilities/$slug/add': typeof AdminCapabilitiesSlugAddRoute
  '/admin/capabilities/$slug/edit': typeof AdminCapabilitiesSlugEditRoute
  '/admin/jobs/$slug/edit': typeof AdminJobsSlugEditRoute
  '/dashboard/suggestions': typeof AuthedDashboardSuggestionsIndexRoute
  '/capabilities/$slug': typeof PublicCapabilitiesSlugIndexRoute
  '/jobs/$slug': typeof PublicJobsSlugIndexRoute
  '/admin/capabilities/$slug': typeof AdminCapabilitiesSlugIndexRoute
  '/admin/jobs/$slug': typeof AdminJobsSlugIndexRoute
  '/admin/capabilities/$slug/$subslug/edit': typeof AdminCapabilitiesSlugSubslugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/capabilities/add': typeof AdminCapabilitiesAddRoute
  '/admin/jobs/add': typeof AdminJobsAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_public/capabilities/': typeof PublicCapabilitiesIndexRoute
  '/_public/jobs/': typeof PublicJobsIndexRoute
  '/_public/reports/': typeof PublicReportsIndexRoute
  '/_public/technologies/': typeof PublicTechnologiesIndexRoute
  '/admin/capabilities/': typeof AdminCapabilitiesIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/_public/capabilities/$slug/$subslug': typeof PublicCapabilitiesSlugSubslugRoute
  '/admin/capabilities/$slug/add': typeof AdminCapabilitiesSlugAddRoute
  '/admin/capabilities/$slug/edit': typeof AdminCapabilitiesSlugEditRoute
  '/admin/jobs/$slug/edit': typeof AdminJobsSlugEditRoute
  '/_authed/dashboard/suggestions/': typeof AuthedDashboardSuggestionsIndexRoute
  '/_public/capabilities/$slug/': typeof PublicCapabilitiesSlugIndexRoute
  '/_public/jobs/$slug/': typeof PublicJobsSlugIndexRoute
  '/admin/capabilities/$slug/': typeof AdminCapabilitiesSlugIndexRoute
  '/admin/jobs/$slug/': typeof AdminJobsSlugIndexRoute
  '/admin/capabilities/$slug/$subslug/edit': typeof AdminCapabilitiesSlugSubslugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/verify-email'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/admin/'
    | '/admin/capabilities/add'
    | '/admin/jobs/add'
    | '/api/auth/$'
    | '/dashboard/'
    | '/capabilities/'
    | '/jobs/'
    | '/reports/'
    | '/technologies/'
    | '/admin/capabilities/'
    | '/admin/jobs/'
    | '/capabilities/$slug/$subslug'
    | '/admin/capabilities/$slug/add'
    | '/admin/capabilities/$slug/edit'
    | '/admin/jobs/$slug/edit'
    | '/dashboard/suggestions/'
    | '/capabilities/$slug/'
    | '/jobs/$slug/'
    | '/admin/capabilities/$slug/'
    | '/admin/jobs/$slug/'
    | '/admin/capabilities/$slug/$subslug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/verify-email'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/admin/capabilities/add'
    | '/admin/jobs/add'
    | '/api/auth/$'
    | '/dashboard'
    | '/capabilities'
    | '/jobs'
    | '/reports'
    | '/technologies'
    | '/admin/capabilities'
    | '/admin/jobs'
    | '/capabilities/$slug/$subslug'
    | '/admin/capabilities/$slug/add'
    | '/admin/capabilities/$slug/edit'
    | '/admin/jobs/$slug/edit'
    | '/dashboard/suggestions'
    | '/capabilities/$slug'
    | '/jobs/$slug'
    | '/admin/capabilities/$slug'
    | '/admin/jobs/$slug'
    | '/admin/capabilities/$slug/$subslug/edit'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/verify-email'
    | '/_public/about'
    | '/_public/privacy'
    | '/_public/terms'
    | '/_public/'
    | '/admin/'
    | '/admin/capabilities/add'
    | '/admin/jobs/add'
    | '/api/auth/$'
    | '/_authed/dashboard/'
    | '/_public/capabilities/'
    | '/_public/jobs/'
    | '/_public/reports/'
    | '/_public/technologies/'
    | '/admin/capabilities/'
    | '/admin/jobs/'
    | '/_public/capabilities/$slug/$subslug'
    | '/admin/capabilities/$slug/add'
    | '/admin/capabilities/$slug/edit'
    | '/admin/jobs/$slug/edit'
    | '/_authed/dashboard/suggestions/'
    | '/_public/capabilities/$slug/'
    | '/_public/jobs/$slug/'
    | '/admin/capabilities/$slug/'
    | '/admin/jobs/$slug/'
    | '/admin/capabilities/$slug/$subslug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/capabilities/': {
      id: '/admin/capabilities/'
      path: '/capabilities'
      fullPath: '/admin/capabilities/'
      preLoaderRoute: typeof AdminCapabilitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/technologies/': {
      id: '/_public/technologies/'
      path: '/technologies'
      fullPath: '/technologies/'
      preLoaderRoute: typeof PublicTechnologiesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/reports/': {
      id: '/_public/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof PublicReportsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/jobs/': {
      id: '/_public/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof PublicJobsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/capabilities/': {
      id: '/_public/capabilities/'
      path: '/capabilities'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof PublicCapabilitiesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/add': {
      id: '/admin/jobs/add'
      path: '/jobs/add'
      fullPath: '/admin/jobs/add'
      preLoaderRoute: typeof AdminJobsAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/capabilities/add': {
      id: '/admin/capabilities/add'
      path: '/capabilities/add'
      fullPath: '/admin/capabilities/add'
      preLoaderRoute: typeof AdminCapabilitiesAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/$slug/': {
      id: '/admin/jobs/$slug/'
      path: '/jobs/$slug'
      fullPath: '/admin/jobs/$slug/'
      preLoaderRoute: typeof AdminJobsSlugIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/capabilities/$slug/': {
      id: '/admin/capabilities/$slug/'
      path: '/capabilities/$slug'
      fullPath: '/admin/capabilities/$slug/'
      preLoaderRoute: typeof AdminCapabilitiesSlugIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/jobs/$slug/': {
      id: '/_public/jobs/$slug/'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug/'
      preLoaderRoute: typeof PublicJobsSlugIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/capabilities/$slug/': {
      id: '/_public/capabilities/$slug/'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug/'
      preLoaderRoute: typeof PublicCapabilitiesSlugIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/dashboard/suggestions/': {
      id: '/_authed/dashboard/suggestions/'
      path: '/dashboard/suggestions'
      fullPath: '/dashboard/suggestions/'
      preLoaderRoute: typeof AuthedDashboardSuggestionsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/admin/jobs/$slug/edit': {
      id: '/admin/jobs/$slug/edit'
      path: '/jobs/$slug/edit'
      fullPath: '/admin/jobs/$slug/edit'
      preLoaderRoute: typeof AdminJobsSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/capabilities/$slug/edit': {
      id: '/admin/capabilities/$slug/edit'
      path: '/capabilities/$slug/edit'
      fullPath: '/admin/capabilities/$slug/edit'
      preLoaderRoute: typeof AdminCapabilitiesSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/capabilities/$slug/add': {
      id: '/admin/capabilities/$slug/add'
      path: '/capabilities/$slug/add'
      fullPath: '/admin/capabilities/$slug/add'
      preLoaderRoute: typeof AdminCapabilitiesSlugAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/capabilities/$slug/$subslug': {
      id: '/_public/capabilities/$slug/$subslug'
      path: '/capabilities/$slug/$subslug'
      fullPath: '/capabilities/$slug/$subslug'
      preLoaderRoute: typeof PublicCapabilitiesSlugSubslugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/capabilities/$slug/$subslug/edit': {
      id: '/admin/capabilities/$slug/$subslug/edit'
      path: '/capabilities/$slug/$subslug/edit'
      fullPath: '/admin/capabilities/$slug/$subslug/edit'
      preLoaderRoute: typeof AdminCapabilitiesSlugSubslugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardSuggestionsIndexRoute: typeof AuthedDashboardSuggestionsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardSuggestionsIndexRoute: AuthedDashboardSuggestionsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCapabilitiesIndexRoute: typeof PublicCapabilitiesIndexRoute
  PublicJobsIndexRoute: typeof PublicJobsIndexRoute
  PublicReportsIndexRoute: typeof PublicReportsIndexRoute
  PublicTechnologiesIndexRoute: typeof PublicTechnologiesIndexRoute
  PublicCapabilitiesSlugSubslugRoute: typeof PublicCapabilitiesSlugSubslugRoute
  PublicCapabilitiesSlugIndexRoute: typeof PublicCapabilitiesSlugIndexRoute
  PublicJobsSlugIndexRoute: typeof PublicJobsSlugIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCapabilitiesIndexRoute: PublicCapabilitiesIndexRoute,
  PublicJobsIndexRoute: PublicJobsIndexRoute,
  PublicReportsIndexRoute: PublicReportsIndexRoute,
  PublicTechnologiesIndexRoute: PublicTechnologiesIndexRoute,
  PublicCapabilitiesSlugSubslugRoute: PublicCapabilitiesSlugSubslugRoute,
  PublicCapabilitiesSlugIndexRoute: PublicCapabilitiesSlugIndexRoute,
  PublicJobsSlugIndexRoute: PublicJobsSlugIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCapabilitiesAddRoute: typeof AdminCapabilitiesAddRoute
  AdminJobsAddRoute: typeof AdminJobsAddRoute
  AdminCapabilitiesIndexRoute: typeof AdminCapabilitiesIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminCapabilitiesSlugAddRoute: typeof AdminCapabilitiesSlugAddRoute
  AdminCapabilitiesSlugEditRoute: typeof AdminCapabilitiesSlugEditRoute
  AdminJobsSlugEditRoute: typeof AdminJobsSlugEditRoute
  AdminCapabilitiesSlugIndexRoute: typeof AdminCapabilitiesSlugIndexRoute
  AdminJobsSlugIndexRoute: typeof AdminJobsSlugIndexRoute
  AdminCapabilitiesSlugSubslugEditRoute: typeof AdminCapabilitiesSlugSubslugEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCapabilitiesAddRoute: AdminCapabilitiesAddRoute,
  AdminJobsAddRoute: AdminJobsAddRoute,
  AdminCapabilitiesIndexRoute: AdminCapabilitiesIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminCapabilitiesSlugAddRoute: AdminCapabilitiesSlugAddRoute,
  AdminCapabilitiesSlugEditRoute: AdminCapabilitiesSlugEditRoute,
  AdminJobsSlugEditRoute: AdminJobsSlugEditRoute,
  AdminCapabilitiesSlugIndexRoute: AdminCapabilitiesSlugIndexRoute,
  AdminJobsSlugIndexRoute: AdminJobsSlugIndexRoute,
  AdminCapabilitiesSlugSubslugEditRoute: AdminCapabilitiesSlugSubslugEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
